export const options = [
    {
      value: "Certification Services",
      label: "Certification Services",
      isDisabled: true,
    },
    { value: "Start-Up India Certificate", label: "Start-Up India Certificate" },
    { value: "MSME/UYDAM Certificate", label: "MSME/UYDAM Certificate 3" },
    { value: "ISO Certificate", label: "ISO Certificate" },
    { value: "IEC CODE Certificate", label: "IEC CODE Certificate" },
    { value: "BIS Certificate", label: "BIS Certificate" },
    { value: "NSIC Certificate", label: "NSIC Certificate" },
    { value: "FSSAI Certificate", label: "FSSAI Certificate" },
    { value: "APEDA Certificate", label: "APEDA Certificate" },
    { value: "GST Certificate", label: "GST Certificate" },
    {
      value: "Documentation Services",
      label: "Documentation Services",
      isDisabled: true,
    },
    { value: "Pitch Deck Development", label: "Pitch Deck Development" },
    { value: "Financial Modeling", label: "Financial Modeling" },
    { value: "DPR Developmen", label: "DPR Developmen" },
    { value: "CMA Report Development", label: "CMA Report Development" },
    { value: "Company Profile", label: "Company Profile" },
    { value: "Company Brochure", label: "Company Brochure" },
    { value: "Product Catalog", label: "Product Catalog" },
    {
      value: "Fund Raising Support Services",
      label: "Fund Raising Support Services",
      isDisabled: true,
    },
    { value: "Seed Funding Support", label: "Seed Funding Support" },
    { value: "Angel Funding Support", label: "Angel Funding Support" },
    { value: "VC Funding Support", label: "VC Funding Support" },
    { value: "Crowd Funding Support", label: "Crowd Funding Support" },
    { value: "Government Funding Support", label: "Government Funding Support" },
    { value: "Digital Marketing", label: "Digital Marketing", isDisabled: true },
    { value: "SEO Services", label: "SEO Services" },
    { value: "Branding Services", label: "Branding Services" },
    {
      value: "Social Promotion Management",
      label: "Social Promotion Management",
    },
    { value: "Email Marketing", label: "Email Marketing" },
    { value: "Digital Content", label: "Digital Content" },
    { value: "Lead Generation", label: "Lead Generation" },
    { value: "Whatsapp Marketing", label: "Whatsapp Marketing" },
    { value: "IT Services", label: "IT Services", isDisabled: true },
    { value: "Website Development", label: "Website Development" },
    { value: "App Design & Development", label: "App Design & Development" },
    {
      value: "Web Application Development",
      label: "Web Application Development",
    },
    { value: "Software Development", label: "Software Development" },
    { value: "CRM Development", label: "CRM Development" },
    { value: "ERP Development", label: "ERP Development" },
    { value: "E-Commerce Website", label: "E-Commerce Website" },
    { value: "Product Development", label: "Product Development" },
    {
      value: "Business Registration",
      label: "Business Registration",
      isDisabled: true,
    },
    {
      value: "Sole Proprietorship Registration",
      label: "Sole Proprietorship Registration",
    },
    {
      value: "Partnership Firm Registration",
      label: "Partnership Firm Registration",
    },
    { value: "LLP Firm Registration", label: "LLP Firm Registration" },
    {
      value: "Private Limited Registration",
      label: "hPrivate Limited Registrationh",
    },
    {
      value: "Public Company Registration",
      label: "Public Company Registration",
    },
    { value: "Nidhi Company Registration", label: "Nidhi Company Registration" },
    {
      value: "Producer Company Registration",
      label: "Producer Company Registration ",
    },
    { value: "Trademark & IP", label: "Trademark & IP", isDisabled: true },
    { value: "Trademark Registration", label: "Trademark Registration" },
    { value: "Copyright Registration", label: "Copyright Registration" },
    { value: "Patent Registration", label: "Patent Registration" },
  
    // Add more options as needed
  ];